language: node_js
node_js:
  - "14"
dist: bionic

addons:
  chrome: stable

script:
  - commitlint-travis
  - npm run lint
  - npm run test:ci
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)